/* Generated By:JJTree&JavaCC: Do not edit this line. XmlConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 6;
  /** RegularExpression Id. */
  int OpenT = 7;
  /** RegularExpression Id. */
  int ClosedT = 8;
  /** RegularExpression Id. */
  int FS = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int DQ = 12;
  /** RegularExpression Id. */
  int SL = 13;
  /** RegularExpression Id. */
  int DIG = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int ALPHANUM = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "<ID>",
    "\",\"",
    "\"\\\"\"",
    "\"</\"",
    "<DIG>",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUM>",
  };

}
