/* Generated By:JavaCC: Do not edit this line. XmlTreeConstants.java Version 7.0.12 */
public interface XmlTreeConstants
{
  public int JJTD = 0;
  public int JJTS = 1;
  public int JJTA = 2;
  public int JJTT = 3;
  public int JJTVALUE = 4;
  public int JJTDIGIT = 5;
  public int JJTOT = 6;
  public int JJTCT = 7;
  public int JJTTEXT = 8;
  public int JJTSL = 9;


  public String[] jjtNodeName = {
    "D",
    "S",
    "A",
    "T",
    "Value",
    "Digit",
    "OT",
    "CT",
    "Text",
    "SL",
  };
}
/* JavaCC - OriginalChecksum=a2dd030dd81714c36275ecb99aa195ae (do not edit this line) */
